### ISSUE TITLE
stacklevel

### ISSUE THREAD

**Issue by artgoldberg** [vforgione/logging2#8]
Hi

Does logging2 plan to support `stacklevel`, like [logging](https://docs.python.org/3/library/logging.html)? That makes it easy to report the file/line of logging calls made through a wrapper.

Thanks
Arthur

**Comment by vforgione** [comment]
Like your other bug, this may be a documentation problem. The current version supports the following:

* `timestamp` for an ISO timestamp
* `level` for the message verbosity/priority
* `name` for the logger's name
* `message` for the user message
* `source` for the source file name
* `function` for the calling function name
* `line` for the line number
* `process` for the operating PID

It's all here: https://github.com/vforgione/logging2/blob/master/logging2/loggers.py#L216-L231

It's been a long while since I've taken a deep dive into the standard logger, so I'm not sure what else they provide. But I'm pretty sure that I tried to keep feature parity here for what they provide out of the box.

The big thing that I was trying to accomplish here was to simplify adding additional metadata and dynamic content to log messages. I had a Flask app that I wanted to throw request IDs into, and I had to use some crazy, non-obvious stuff to make it happen.

I'm scratching a few itches again now with a new version. I'll try to make this stuff a little more obvious.

**Comment by vforgione** [comment]
I should probably also point out that I don't do a whole lot of Python work anymore -- I moved into Elixir for my backend work at my last job, and for data stuff I've been working with more R and Julia devs lately (although I have been pushing them to adopt Python more).

Truth be told, I'm in a management position now for my day job which has the unfortunate side effect of almost never writing code. Add in a new baby, and I get about 15 minutes to write code every couple months :(

I saw that you're using this (or were using, not sure) for a project. If you need something more stable then you may want to just use the stdlib logging lib, warts and all. I'm going to try to work on this when I can, but as I mentioned I've got some competing interests.

**Comment by artgoldberg** [comment]
Hi Vince

I appreciate your replies.

`stacklevel` is a trick that grabs things like filename and line number from a specified number of calls down the call stack so that logging can be made through wrapper functions.

Congrats on your promotion to management and your new child!

And thanks for the heads up about your lack of bandwidth to make changes to `logging2`. We'll plan accordingly.

Regards
Arthur

**Comment by vforgione** [comment]
I finally had a chance to look at where the stdlib logger is at these days, and they've made some decent improvements. I still generally feel like much of it is overkill though.

That being said, I think for the `stacklevel` use case using that is the best option. I'm looking at my code here and that's a level of depth that I don't think this should aim for. To be honest, I'm a little dubious of the utility of this library over some simple wrapper functions around `stdout` and `stderr`. The more I look at this the more I think I was just really frustrated with having to implement some custom functionality around logging's filters -- and even then that was a byproduct of working on a really shitty Flask app.
